apiVersion: v3
name: eg
description: The Helm chart for Envoy Gateway.
type: application

version: 0.1.3
appVersion: "0.3.0"

maintainers: 
  - name: envoy-gateway-maintainers
    url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS.md

keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway

home: https://gateway.envoyproxy.io/

sources:
  - https://github.com/envoyproxy/gateway
