apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: envoy-gateway
  name: envoy-gateway-metrics-service
  namespace: envoy-gateway-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: envoy-gateway
