name: Auto Request Review

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from team
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');
            const context = github.context;
            const pullRequestNumber = context.payload.pull_request.number;
            const repo = context.repo;
            await github.rest.pulls.requestReviewers({
              ...repo,
              pull_number: pullRequestNumber,
              reviewers: ['Xunzhuo']
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}
