name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/eg/Chart.yaml"

permissions: {}
jobs:
  release:
    permissions:
      contents: write 

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get chart version
        id: chart_version
        run: |
          set -euo pipefail
          chart_version="$(grep -Po "(?<=^version: ).+" charts/eg/Chart.yaml)"
          echo "::set-output name=version::${chart_version}"
      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@b97ce03a10d9bdbb07beb491c76a5a01d78cd3ef
        with:
          path: charts/eg/CHANGELOG.md
          version: "v${{ steps.chart_version.outputs.version }}"

      - name: Create release notes
        run: |
          set -euo pipefail
          cat <<"EOF" > charts/eg/RELEASE.md
          ${{ steps.changelog_reader.outputs.changes }}
          EOF
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set-up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "eg-helm-chart-{{ .Version }}"
          CR_RELEASE_NOTES_FILE: RELEASE.md
          CR_MAKE_RELEASE_LATEST: false
