name: Experimental Conformance Test
on:
  push:
    paths:
    - 'charts/gateway-helm/crds/gatewayapi-crds.yaml'
  pull_request:
    paths:
    - 'charts/gateway-helm/crds/gatewayapi-crds.yaml'

jobs:
  experimental-conformance-test:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ v1.26.6, v1.27.3, v1.28.0 ]
    steps:
    - uses: actions/checkout@v3
    - uses: ./tools/github-actions/setup-deps

    - name: Comment Conformance Report
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })

    # gateway api experimental conformance
    - name: Run Experimental Conformance Tests
      env:
        CONFORMANCE_REPORT_PATH: conformance-report-k8s-${{ matrix.version }}.yaml
        KIND_NODE_TAG: ${{ matrix.version }}
        IMAGE_PULL_POLICY: IfNotPresent
      run: make experimental-conformance

    - name: Upload Conformance Report
      uses: actions/upload-artifact@v3
      with:
        name: conformance-report-k8s-${{ matrix.version }}
        path: ./test/conformance/conformance-report-k8s-${{ matrix.version }}.yaml

    - name: Comment Conformance Report
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          const filePath = path.join(process.env.GITHUB_WORKSPACE, './test/conformance/conformance-report-k8s-${{ matrix.version }}.yaml');
          const fileContent = fs.readFileSync(filePath, 'utf8');

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: fileContent
          })
