name: Kube Prow Bot
on:
  issue_comment:
    types:
      - created

  pull_request_review_comment:
    types:
      - created

  issues:
    types:
      - opened

  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types:
      - opened

env:
  # This commands is for anyone who can use it
  COMMON_PLUGINS: |-
    assign
    kind
    cc
  # This commands is for author of issue or PR
  AUTHOR_PLUGINS: |-
    retest
  # This commands is for organization member or repository member
  MEMBERS_PLUGINS: |-
    good-first-issue
    help-wanted
    close
    reopen
    retest
  # This commands is for in the REVIEWERS environment variable
  REVIEWERS_PLUGINS: |-
    area
    lgtm
    hold
  # This commands is for in the APPROVERS environment variable
  APPROVERS_PLUGINS: |-
    merge
    approve
    rebase
  # This commands is for in the MAINTAINERS environment variable
  MAINTAINERS_PLUGINS: |-
    milestone
    priority

  # REVIEWERS: |-
  #   Xunzhuo
  # APPROVERS: |-
  #   Xunzhuo
  MAINTAINERS: |-
    AliceProxy
    arkodg
    danehans
    skriss
    Xunzhuo
    youngnick
    zirain

  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPOSITORY: ${{ github.repository }}
  DETAILS: |-
    <details>
    <summary>Details</summary>
    Instructions for interacting with me using comments are available here.
    If you have questions or suggestions related to my behavior, please file an issue against the [kube-prow-bot](https://github.com/Xunzhuo/kube-prow-bot) repository.
    </details>

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  actions: write
  checks: read
  contents: write
  deployments: none
  id-token: none
  issues: write
  discussions: read
  packages: none
  pages: none
  pull-requests: write
  repository-projects: read
  security-events: none
  statuses: read

jobs:
  bot:
    name: Bot
    runs-on: ubuntu-latest
    steps:
      - name: Issue Opened
        uses: Xunzhuo/kube-prow-bot@v1.0.0
        if: ${{ github.event_name == 'issues' }}
        env:
          LOGIN: ${{ github.event.issue.user.login }}
          AUTHOR: ${{ github.event.issue.user.login }}
          MESSAGE: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          AUTHOR_ASSOCIATION: ${{ github.event.issue.author_association }}
          ISSUE_KIND: issue
          TYPE: created
          GREETING: |-
            Hi @${{ github.event.issue.user.login }},
            Thanks for opening an issue! 🎉

      - name: PR Opened
        uses: Xunzhuo/kube-prow-bot@v1.0.0
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          LOGIN: ${{ github.event.pull_request.user.login }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          MESSAGE: ${{ github.event.pull_request.body }}
          ISSUE_NUMBER: ${{ github.event.pull_request.number }}
          AUTHOR_ASSOCIATION: ${{ github.event.pull_request.author_association }}
          ISSUE_KIND: pr
          TYPE: created
          GREETING: |-
            Hi @${{ github.event.pull_request.user.login }},
            Thanks for your pull request! 🎉
            If the PR is ready, use the `/cc` command to assign reviewer to review. 

      - name: Issue Commented
        uses: Xunzhuo/kube-prow-bot@v1.0.0
        if: ${{ github.event_name == 'issue_comment' && !github.event.issue.pull_request }}
        env:
          LOGIN: ${{ github.event.comment.user.login }}
          AUTHOR: ${{ github.event.issue.user.login }}
          MESSAGE: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
          ISSUE_KIND: issue
          TYPE: comment

      - name: PR Review Commented
        uses: Xunzhuo/kube-prow-bot@v1.0.0
        if: ${{ github.event_name == 'pull_request_review_comment' }}
        env:
          LOGIN: ${{ github.event.comment.user.login }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          MESSAGE: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.pull_request.number }}
          AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
          ISSUE_KIND: pr
          TYPE: comment

      - name: PR Commented
        uses: Xunzhuo/kube-prow-bot@v1.0.0
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
        env:
          LOGIN: ${{ github.event.comment.user.login }}
          AUTHOR: ${{ github.event.issue.user.login }}
          MESSAGE: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
          ISSUE_KIND: pr
          TYPE: comment
