name: Canary Release

on:
  push:
    branches:
    - "main"
    paths-ignore:
    - "**/*.png"

jobs:
  canary-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate Release Manifests
      run: make generate-manifests IMAGE=envoyproxy/gateway-dev TAG=latest OUTPUT_DIR=release-artifacts

    # Ignore the error from the first time canary release deletion.
    # We do not have the release at first, after that, the error will not appear again.
    - name: Delete Canary Release
      continue-on-error: true
      run: |
        gh release delete latest --repo $GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository_owner }}/${{ github.event.repository.name }}

    # Same as above, ignore the error from the first time canary tag deletion.
    # We do not have the tag at first, after that, the error will not appear again.
    - name: Delete Canary Tag
      continue-on-error: true
      run:
        gh api --method DELETE /repos/$GITHUB_REPOSITORY/git/refs/tags/latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository_owner }}/${{ github.event.repository.name }}

    - name: Recreate Canary Release and Tag
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: true
        tag_name: latest
        files: |
          release-artifacts/install.yaml
          release-artifacts/quickstart.yaml
        body: |
          This is a "Canary Release" of **Envoy Gateway**, which contains the most recent commits on our main branch.
          
          Canary is **not stable**.

          It is only intended for developers wishing to try out the latest features in Envoy Gateway, some of which may not be fully implemented.
